### ISSUE TITLE
How to send logs from external VM's using Logstash to opensihft elasticsearch.. 

### ISSUE THREAD

**Issue by himmatb** [openshift/origin-aggregated-logging#1104]
I have exposed Elasticsearch API to the external world using routes with below option in ansible inventory : 

#expose Elasticsearch as a reencrypt route

openshift_logging_es_allow_external=true
openshift_logging_es_hostname=logging-es.xxxxxx.com

openshift_logging_es_ca_ext=/root/es-kibana-cert/xyz.cer
openshift_logging_es_cert=/root/es-kibana-cert/xyz.crt
openshift_logging_es_key=/root/es-kibana-cert/xyz.pem

I want to send logs of one of application running on external VM into to openshift elasticsearch to view on KIBANA. 
I have tried with logstash to use to forward logs to elasticsearch but its getting failed.

Please help me..

**Comment by richm** [comment]
any logstash errors?
where di dyou get the ca cert, es cert, and es key?

**Comment by himmatb** [comment]
I have below configuration for logstash: 

input {
  file {	
	path => "C:\Program Files\NCR APTRA\Aptra Activate\Logs\logfile20180419.log"	
	start_position => "beginning"
	sincedb_path => "NUL"
	ignore_older => 0
	codec => multiline {
		pattern => "Log Entry:"
		negate => true
		what => "previous"
	}
  }
}

output {
 elasticsearch {
    hosts => [ "https://logging-es.openshift.enbduat.com" ]
    ssl => true
    ssl_certificate_verification => false
    cacert => 'C:\Users\SSTAdmin1\logstash-6.2.4\logstash-6.2.4\bin\1ca.txt'
    index => "logstash-%{+YYY.MM.dd}"
  }
}
output {
  stdout {}
}
Without elasticsearch output I am able to parse file and can see stdout for all the logs entries.

I have applied these certificate through ansible playbook and picked them up from TLS settings from opesnshift route.

Below is logstash output:

[2018-04-23T14:26:14,151][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/modules/fb_apache/configuration"}
[2018-04-23T14:26:14,167][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/modules/netflow/configuration"}
[2018-04-23T14:26:14,329][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-04-23T14:26:14,724][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.4"}
[2018-04-23T14:26:14,987][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-04-23T14:26:17,531][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-04-23T14:26:17,597][WARN ][logstash.outputs.elasticsearch] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2018-04-23T14:26:17,930][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://logging-es.openshift.enbduat.com:9200/]}}
[2018-04-23T14:26:17,941][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://logging-es.openshift.enbduat.com:9200/, :path=>"/"}
[2018-04-23T14:26:28,099][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://logging-es.openshift.enbduat.com:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://logging-es.openshift.enbduat.com:9200/][Manticore::ConnectTimeout] connect timed out"}
[2018-04-23T14:26:28,150][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-04-23T14:26:28,166][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Template file '' could not be found!", :class=>"ArgumentError", :backtrace=>["C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/template_manager.rb:31:in `read_template_file'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/template_manager.rb:17:in `get_template'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/template_manager.rb:7:in `install_template'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:96:in `install_template'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:26:in `register'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/output_delegator.rb:42:in `register'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:730:in `maybe_setup_out_plugins'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"]}
[2018-04-23T14:26:28,178][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://logging-es.openshift.enbduat.com"]}
[2018-04-23T14:26:28,674][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"main", :thread=>"#<Thread:0x186eca1 run>"}
[2018-04-23T14:26:28,741][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-04-23T14:26:29,375][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `<' for nil:NilClass>, :backtrace=>["C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:222:in `get_event_type'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:47:in `event_action_tuple'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:36:in `block in multi_receive'", "org/jruby/RubyArray.java:2486:in `map'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.1.1-java/lib/logstash/outputs/elasticsearch/common.rb:36:in `multi_receive'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:477:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:476:in `output_batch'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:428:in `worker_loop'", "C:/Users/SSTAdmin1/logstash-6.2.4/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:386:in `block in start_workers'"]}
[2018-04-23T14:26:29,552][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit

**Comment by richm** [comment]
> I am trying to send logs using logstash directly to elasticsearch.

Right - it should work the same way as ovirt/rhv uses fluentd to send logs to elasticsearch.  That is - configure logstash to use the fluentd client cert and key to send logs to the elasticsearch service which is configured with externalIPs.

As for your other questions - they should be answered in the logging documentation - https://docs.openshift.org/3.6/welcome/index.html

If you have general questions, this issue isn't the way to have a general usage conversation.  I would suggest using the openshift users mailing list, especially for questions like "it possible without upgrading oc?".  However, if you run into bugs, please open issues.
