### ISSUE TITLE
origin-logging-fluentd:v3.11.0 broken

### ISSUE THREAD

**Issue by aneagoe** [openshift/origin-aggregated-logging#1823]
The current v3.11.0 tag of origin-logging-fluentd is failing. It has the following SHA:
`sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb`

The error is the following:
```2020-01-28 14:54:45 +0000 [warn]: [container-input] 'encoding' and 'from_encoding' are same encoding. No effect
2020-01-28 14:55:38 +0000 [warn]: [elasticsearch-apps] buffer flush took longer time than slow_flush_log_threshold: elapsed_time=33.5316653335467 slow_flush_log_threshold=20.0 plugin_id="elasticsearch-apps"
2020-01-28 14:56:01 +0000 [warn]: [elasticsearch-apps] buffer flush took longer time than slow_flush_log_threshold: elapsed_time=22.635042862035334 slow_flush_log_threshold=20.0 plugin_id="elasticsearch-apps"
2020-01-28 14:56:03 +0000 [warn]: [elasticsearch-apps] buffer flush took longer time than slow_flush_log_threshold: elapsed_time=24.979070929810405 slow_flush_log_threshold=20.0 plugin_id="elasticsearch-apps"
2020-01-28 14:57:16 +0000 [error]: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - /etc/fluent/metrics/tls.crt"
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-prometheus-1.3.0/lib/fluent/plugin/in_prometheus.rb:68:in `read'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-prometheus-1.3.0/lib/fluent/plugin/in_prometheus.rb:68:in `start'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:203:in `block in start'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:191:in `each'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:178:in `each'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:178:in `lifecycle'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/root_agent.rb:202:in `start'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/engine.rb:274:in `start'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/engine.rb:219:in `run'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/supervisor.rb:805:in `run_engine'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/supervisor.rb:549:in `block in run_worker'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/supervisor.rb:730:in `main_process'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/supervisor.rb:544:in `run_worker'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/bin/fluentd:8:in `<top (required)>'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/bin/fluentd:23:in `load'
  2020-01-28 14:57:16 +0000 [error]: /opt/rh/rh-ruby25/root/usr/local/bin/fluentd:23:in `<main>'
2020-01-28 14:57:16 +0000 [error]: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - /etc/fluent/metrics/tls.crt"
  2020-01-28 14:57:16 +0000 [error]: suppressed same stacktrace
```
Reverting to SHA `sha256:a21505364c56637277d1d7d88d5953fb489d228502a7d6743154623f182c03d9` and the pod starts up just fine.

**Comment by jcantrill** [comment]
I'm not certain from where you sourced this image but regardless v3.11.0 would be extremely old.  The latest release is something like 3.11.154.  Also, this error: `"No such file or directory @ rb_sysopen - /etc/fluent/metrics/tls.crt"` indicates there is a configuration issue, not image.  It looks like you are trying to run the image but haven't mounted certs in the proper location in order for the metrics configuration to work properly.

**Comment by aneagoe** [comment]
Hi @jcantrill. I'm not sure where you found tag v3.11.154... I can only see three tags looking at https://hub.docker.com/r/openshift/origin-logging-fluentd/tags?page=1&name=v3.11
Further, there's no difference between working/non-working fluentd except image. I mean, it's sufficient for me to revert to the working Image ID and the pod starts successfully. 
Below a comparison between non-working (first) and working images:
```
andrei@andrei-nb:~$ oc describe pod logging-fluentd-n54tp | grep 'Image ID'
    Image ID:       docker-pullable://docker.io/openshift/origin-logging-fluentd@sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
andrei@andrei-nb:~$ oc describe pod logging-fluentd-r47lk | grep 'Image ID'
    Image ID:       docker-pullable://docker.io/openshift/origin-logging-fluentd@sha256:a21505364c56637277d1d7d88d5953fb489d228502a7d6743154623f182c03d9
```

The okd 3.11 daemon-set specifies `docker.io/openshift/origin-logging-fluentd:v3.11.0` as image by default.

**Comment by jcantrill** [comment]
We no longer push images to dockerhub.  Image mirroring is described here[1] 

[1] https://github.com/openshift/release/tree/master/core-services/image-mirroring

**Comment by aneagoe** [comment]
Are you suggesting to post the issue under openshift/release? I've taken a quick look at things but it's not very easy to understand the whole process used to release/mirror/tag these images in docker hub. 
I've just found that the v3.11.0 and v4.0.0 point actually to the same digest:
```
 andrei@andrei-nb:~$ docker pull openshift/origin-logging-fluentd:v3.11.0
v3.11.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Image is up to date for openshift/origin-logging-fluentd:v3.11.0
docker.io/openshift/origin-logging-fluentd:v3.11.0
andrei@andrei-nb:~$ docker pull openshift/origin-logging-fluentd:v4.0.0
v4.0.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Image is up to date for openshift/origin-logging-fluentd:v4.0.0
docker.io/openshift/origin-logging-fluentd:v4.0.0
```
Taking a closer look at the affected image, I see major discrepancies between ruby gems. Below a small sample of the most relevant differences between working(top) and non-working images:
```
< fluent-plugin-elasticsearch-1.17.2
< fluent-plugin-kubernetes_metadata_filter-1.2.2
< fluent-plugin-prometheus-0.4.0
---
> fluent-plugin-elasticsearch-3.4.0
> fluent-plugin-kubernetes_metadata_filter-2.1.6
> fluent-plugin-prometheus-1.3.0
```

So at this point, the problem is clear, I'm just not sure what's the right place to report it to get this corrected.

**Comment by jcantrill** [comment]
> So at this point, the problem is clear, I'm just not sure what's the right place to report it to get this corrected.

This is not an eror: Images are published to https://quay.io/repository/openshift/origin-logging-fluentd?tab=tags . Please use the latest 3.11 image to see if it resolves your issue

**Comment by aneagoe** [comment]
@jcantrill I'm sorry to say but in quay.io it's the same situation. Please see below:
```
andrei@andrei-nb:~$ docker pull quay.io/openshift/origin-logging-fluentd:v3.11.0
v3.11.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Downloaded newer image for quay.io/openshift/origin-logging-fluentd:v3.11.0
quay.io/openshift/origin-logging-fluentd:v3.11.0
```
This is consistent with https://quay.io/repository/openshift/origin-logging-fluentd?tab=tags which shows that v3.11, v3.11.0, v4.0, v4.0.0 all have the same underlying image.

**Comment by jcantrill** [comment]
@aneagoe so elephant in the room, does:
* the the container have access to: `2020-01-28 14:57:16 +0000 [error]: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - /etc/fluent/metrics/tls.crt"`
* Is the file a valid cert?
* How are you deploying the collector?  Can you provide your ansible inventory file? The version of the playbooks you are using?

**Comment by aneagoe** [comment]
@jcantrill There is no such file and there shouldn't be one in v3.11.0. Please see below the output from the working pod:
```
andrei@andrei-nb:~/code$ oc get pod logging-fluentd-r47lk
NAME                    READY     STATUS    RESTARTS   AGE
logging-fluentd-r47lk   1/1       Running   0          7d
andrei@andrei-nb:~/code$ oc describe pod logging-fluentd-r47lk | grep 'Image ID'
    Image ID:       docker-pullable://docker.io/openshift/origin-logging-fluentd@sha256:a21505364c56637277d1d7d88d5953fb489d228502a7d6743154623f182c03d9
andrei@andrei-nb:~/code$ oc rsh logging-fluentd-r47lk ls /etc/fluent/metrics/tls.crt
ls: cannot access /etc/fluent/metrics/tls.crt: No such file or directory
command terminated with exit code 2
andrei@andrei-nb:~/code$ oc rsh logging-fluentd-r47lk ls -lsa /etc/fluent/
total 4
0 drwxr-xr-x. 1 root root   35 Jan 28 15:34 .
0 drwxr-xr-x. 1 root root   88 Jan 28 15:34 ..
0 drwxrwxr-x. 1 root root   74 Jan 28 15:34 configs.d
0 lrwxrwxrwx. 1 root root   38 Oct  3 19:03 fluent.conf -> /etc/fluent/configs.d/user/fluent.conf
0 drwxrwxrwt. 3 root root  200 Jan 28 15:34 keys
4 drwxr-xr-x. 2 root root 4096 Oct  3 19:03 plugin
```
As per https://github.com/openshift/origin-aggregated-logging/issues/1823#issuecomment-580275057, the current image with tag v3.11.0 has much newer packages. So what I'm trying to say is that the real v4.0 image was also tagged with v3.11.0 and not the other way around. 
The collector was deployed via the ansible playbooks from https://github.com/openshift/openshift-ansible (branch release-3.11). Only after I added some new nodes to the cluster at a later time, this started to surface (since they pulled the wrong image). 

Please let me know if you would require any additional information.

**Comment by jcantrill** [comment]
> @jcantrill There is no such file and there shouldn't be one in v3.11.0. Please see below the output from the working pod:

> As per [#1823 (comment)](https://github.com/openshift/origin-aggregated-logging/issues/1823#issuecomment-580275057), the current image with tag v3.11.0 has much newer packages. So what I'm trying to say is that the real v4.0 image was also tagged with v3.11.0 and not the other way around.

Have you considered trying quay.io/openshift/origin-logging-fluentd:v3.11  which is likely the 'latest' 3.11 image instead of the one pegged to v3.11.0

> The logging infrastructure was deployed via the ansible playbooks from https://github.com/openshift/openshift-ansible (branch release-3.11, via playbooks/openshift-logging/config.yml). Only after I added some new nodes to the cluster at a later time, this started to surface (since they pulled the wrong image).

I don't routinely deploy these playbooks any longer but to my knowledge they still are sufficient. Assuming you have the latest 3.11 image you likely will not see this issue as you have noted.

**Comment by aneagoe** [comment]
@jcantrill Of course I did, I even mentioned it earlier (last line of https://github.com/openshift/origin-aggregated-logging/issues/1823#issuecomment-581796056).
For the sake of the argument, please see below:
```
andrei@andrei-nb:~$ docker pull quay.io/openshift/origin-logging-fluentd:v3.11.0
v3.11.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Image is up to date for quay.io/openshift/origin-logging-fluentd:v3.11.0
quay.io/openshift/origin-logging-fluentd:v3.11.0
andrei@andrei-nb:~$ docker pull quay.io/openshift/origin-logging-fluentd:v3.11
v3.11: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Downloaded newer image for quay.io/openshift/origin-logging-fluentd:v3.11
quay.io/openshift/origin-logging-fluentd:v3.11
andrei@andrei-nb:~$ docker pull quay.io/openshift/origin-logging-fluentd:v4.0
v4.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Downloaded newer image for quay.io/openshift/origin-logging-fluentd:v4.0
quay.io/openshift/origin-logging-fluentd:v4.0
andrei@andrei-nb:~$ docker pull quay.io/openshift/origin-logging-fluentd:v4.0.0
v4.0.0: Pulling from openshift/origin-logging-fluentd
Digest: sha256:48f359e3560d85e895e5bb71fccd14348cb2a8a855dc58f8748e3a07dadfc5eb
Status: Downloaded newer image for quay.io/openshift/origin-logging-fluentd:v4.0.0
quay.io/openshift/origin-logging-fluentd:v4.0.0
```.

Something is awfully wrong in the process that controls the build and release for these older images.

**Comment by jcantrill** [comment]
We have identified the offender and a corrected v3.11 image stream should be synced in the hour

**Comment by aneagoe** [comment]
Perfect, works like a charm, thanks for looking into it!

**Comment by uselessidbr** [comment]
The latest image had the same digest as 3.11 and 4.x tag, just make sure they are decoupled to grant that 3.11 will not be updated when latest is updated.
