### ISSUE TITLE
logging-fluentd pod CrashLoopBackOff

### ISSUE THREAD

**Issue by garrotemar** [openshift/origin-aggregated-logging#1825]
Hi:
I have added some nodes to my OKD 3.11 cluster and I observe that the fluentd pods remain in CrashLoopBackOff or Error.
Actual Nodes
logging-fluentd-cmznp                     1/1       Running            0          1h        10.128.1.146   master01.example.com
logging-fluentd-nb9w5                     1/1       Running            0          1h        10.130.1.163   worker01.example.com
logging-fluentd-gw8mp                     1/1       Running            0          1h        10.129.1.220   worker03.example.com
logging-fluentd-fwfnl                     1/1       Running            0          1h        10.131.1.192   worker05.example.com
logging-fluentd-4d5fn                     1/1       Running            0          1h        10.128.3.201   worker07.example.com

New Nodes
logging-fluentd-nkkdd                     0/1       CrashLoopBackOff   26         1h        10.129.2.61    master03.example.com
logging-fluentd-ghqvg                     0/1       Error              13         42m       10.130.2.85    master05.example.com
logging-fluentd-8nswq                     0/1       CrashLoopBackOff   26         1h        10.128.4.183   infra01.example.com
logging-fluentd-qqxkm                     0/1       CrashLoopBackOff   27         1h        10.129.5.210   infra03.example.com
logging-fluentd-6jq5g                     0/1       CrashLoopBackOff   27         1h        10.131.2.207   infra05.example.com

In lof file /var/log/fluentd/fluentd.log

2020-02-03 10:45:46 -0300 [error]: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - /etc/fluent/metrics/tls
.crt"
  2020-02-03 10:45:46 -0300 [error]: suppressed same stacktrace
2020-02-03 10:45:46 -0300 [error]: fluent/log.rb:362:error: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen
- /etc/fluent/metrics/tls.crt"
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-prometheus
-1.3.0/lib/fluent/plugin/in_prometheus.rb:68:in `read'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-prometheus
-1.3.0/lib/fluent/plugin/in_prometheus.rb:68:in `start'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:203:in `block in start'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:191:in `each'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:191:in `block in lifecycle'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:178:in `each'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:178:in `lifecycle'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/root_agent.rb:202:in `start'
  2020-02-03 10:45:46 -0300 [error]: fluent/supervisor.rb:729:main_process: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.4.1/lib/fluent
/engine.rb:274:in `start'
......

I see to that images in a server that the fluentd is ok is differente that the other not working.

Example:  ( note the different sizes )

Server that not working fluentd:  docker.io/openshift/origin-logging-fluentd            v3.11.0             edfef3467aef        9 months ago        624 MB

Server that working fluentd: 
docker.io/openshift/origin-logging-fluentd                      v3.11.0             0418678eef95        4 months ago        492 MB

Regards.... Marcelo

**Comment by jcantrill** [comment]
You likely have old images as we no longer publish images to docker but have since moved to regular publishing of images to quay.io

**Comment by garrotemar** [comment]
Hi: understand but the image was pulled from openshift-ansible installation logging.

**Comment by jcantrill** [comment]
Closing as dup of #1823
