### ISSUE TITLE
fluentd - lz4 compression support

### ISSUE THREAD

**Issue by johnny-burak** [openshift/origin-aggregated-logging#1919]
Hi,

I'm trying to add lz4 compression support to fluentd image to be able to use lz4 with kafka2 output plugin.

I took fluentd-4.6 version and building on rhscl/ruby-25-rhel7:latest image. I created custom Dockefile based on Dockerfile.centos7 and Dockerfile. I did it because I have to build an image in an environment with older docker version which is not supporting multi-stage build and also don't have centos7 image available.

To add lz4 compression algorithm support the extlz4 gem is required. Because of an installation in disconnected env I downloaded .gem file from https://rubygems.org/gems/extlz4/versions/0.3 (extlz4-0.3.gem) and during the build I copy the .gem file to ${HOME}/vendored_gem_src/ directory. Then the gem is successfully installed by install-gems.sh script.
The image build is completed successfully.

But when I run the image and the fluend-kafka-plugin is invoked fluentd fail when ruby-kafka tries to load lz4_codec. In fluentd.log is error which is saying: "using lz4 compression requires adding a dependency on the `extlz4` gem to your Gemfile."

I also tried to add dependency to Gemfile in fluentd root folder (the same folder as Dockerfile), but don't see the Gemfile to be used during the build. And also added dependency to vendored_gem_src/ruby-kafka/ruby-kafka.gemspec. The build is succesfull, the gem is installed successfully, but the result is the same.

I then found that the error message is general message when load of the lz4_codec fails:
https://www.rubydoc.info/gems/ruby-kafka/Kafka/LZ4Codec
looks at the load=>object - view source.

I'm out of ideas what to do next, to be able to load lz4_codec successfully. I'm also not a ruby guy.
Any help, any tip would be really aprriciated.

Also could lz4 support be added to fluentd image officialy? I can image there is more people who would use it.

Thanks.

my Dockerfile.rhel7
```
FROM rhscl/ruby-25-rhel7:latest

ENV DATA_VERSION=1.6.0 \
    FLUENTD_VERSION=1.9.2 \
    GEM_HOME=/opt/app-root/src \
    HOME=/opt/app-root/src \
    PATH=/opt/app-root/src/bin:/opt/app-root/bin:$PATH \
    LOGGING_FILE_PATH=/var/log/fluentd/fluentd.log \
    LOGGING_FILE_AGE=10 \
    LOGGING_FILE_SIZE=1024000

USER 0

RUN yum install -y --setopt=tsflags=nodocs \
      make gcc-c++ libffi-devel \
      bc git iproute hostname \
      autoconf automake libtool m4 \
      redhat-rpm-config && \
    yum clean all
 
ADD jemalloc/ ${HOME}/jemalloc/
RUN cd ${HOME}/jemalloc && EXTRA_CFLAGS="$( rpm --eval '%{optflags}' )" ./autogen.sh && \
    make install_lib_shared install_bin && cp COPYING ${HOME}/COPYING.jemalloc && \
    cd ${HOME} && rm -rf jemalloc
 
ADD source.jemalloc /source.jemalloc
RUN bash -c '. /source.jemalloc; echo jemalloc $JEMALLOC_VER >> /contents'
 
ADD install-gems.sh *.patch.sh *.patch vendored_gem_src/ ${HOME}/vendored_gem_src/
COPY extlz4-0.3.gem ${HOME}/vendored_gem_src/extlz4-0.3.gem
 
RUN cd ${HOME}/vendored_gem_src/ && ./install-gems.sh && rm -f *.gem && cd / && rm -rf ${HOME}/vendored_gem_src/
 
RUN mkdir -p /etc/fluent/plugin
ADD configs.d/ /etc/fluent/configs.d/
ADD out_syslog_buffered.rb out_syslog.rb out_rawtcp.rb \
    lib/filter_parse_json_field/lib/*.rb \
    lib/filter_elasticsearch_genid_ext/lib/filter_elasticsearch_genid_ext.rb \
    lib/parser_viaq_host_audit/lib/*.rb \
    lib/fluent-plugin-viaq_data_model/lib/fluent/plugin/*.rb \
    /etc/fluent/plugin/
ADD run.sh generate_syslog_config.rb \
    lib/generate_throttle_configs/lib/*.rb \
    ${HOME}/
COPY utils/** /usr/local/bin/
RUN mkdir -p /etc/fluent/configs.d/{dynamic,user} && \
    chmod 777 /etc/fluent/configs.d/dynamic && \
    ln -s /etc/fluent/configs.d/user/fluent.conf /etc/fluent/fluent.conf

WORKDIR ${HOME}
CMD ["sh", "run.sh"]
```

part of build output
```
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/HISTORY.ja.md
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/LICENSE
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/README.md
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/Rakefile
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/bin/extlz4
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/INSTALL
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/LICENSE
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/NEWS
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/README.md
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/LICENSE
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/README.md
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/liblz4.pc.in
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4frame.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4frame.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4frame_static.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4hc.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/lz4hc.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/xxhash.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/contrib/lz4/lib/xxhash.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/examples/frameapi.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/blockapi.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/depend
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/extconf.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/extlz4.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/extlz4.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/frameapi.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/hashargs.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/hashargs.h
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext/lz4_amalgam.c
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/gemstub.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/lib/extlz4.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/lib/extlz4/compat.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/lib/extlz4/fix-0.1bug.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/lib/extlz4/oldstream.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/lib/extlz4/version.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/test/common.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/test/test_blockapi.rb
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/test/test_frameapi.rb
Building native extensions. This could take a while...
current directory: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext
/opt/rh/rh-ruby25/root/usr/bin/ruby -r ./siteconf20200603-1029-1jx5dpo.rb extconf.rb
checking for whether -I$(srcdir)/../contrib/lz4/lib is accepted as CPPFLAGS... yes
checking for whether -fvisibility=hidden is accepted as CFLAGS... yes
creating Makefile
current directory: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext
make "DESTDIR=" clean
rm -f 
rm -f extlz4.so  *.o  *.bak mkmf.log .*.time
current directory: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext
make "DESTDIR="
gcc -I. -I/opt/rh/rh-ruby25/root/usr/include -I/opt/rh/rh-ruby25/root/usr/include/ruby/backward -I/opt/rh/rh-ruby25/root/usr/include -I. '-DRBEXT_API=__attribute__ ((visibility("default")))' -DRBEXT_VISIBILITY=1    -I./../contrib/lz4/lib -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fvisibility=hidden -m64 -o blockapi.o -c blockapi.c
[91mblockapi.c: In function 'aux_LZ4_compress_fast_continue':
blockapi.c:35:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return (int)aux_thread_call_without_gvl(
            ^
blockapi.c: In function 'aux_LZ4_compressHC_continue':
blockapi.c:57:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return (int)aux_thread_call_without_gvl(
            ^
blockapi.c: In function 'aux_LZ4_decompress_safe_continue':
blockapi.c:79:12: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     return (int)aux_thread_call_without_gvl(
            ^
[0mgcc -I. -I/opt/rh/rh-ruby25/root/usr/include -I/opt/rh/rh-ruby25/root/usr/include/ruby/backward -I/opt/rh/rh-ruby25/root/usr/include -I. '-DRBEXT_API=__attribute__ ((visibility("default")))' -DRBEXT_VISIBILITY=1    -I./../contrib/lz4/lib -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fvisibility=hidden -m64 -o extlz4.o -c extlz4.c
gcc -I. -I/opt/rh/rh-ruby25/root/usr/include -I/opt/rh/rh-ruby25/root/usr/include/ruby/backward -I/opt/rh/rh-ruby25/root/usr/include -I. '-DRBEXT_API=__attribute__ ((visibility("default")))' -DRBEXT_VISIBILITY=1    -I./../contrib/lz4/lib -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fvisibility=hidden -m64 -o frameapi.o -c frameapi.c
gcc -I. -I/opt/rh/rh-ruby25/root/usr/include -I/opt/rh/rh-ruby25/root/usr/include/ruby/backward -I/opt/rh/rh-ruby25/root/usr/include -I. '-DRBEXT_API=__attribute__ ((visibility("default")))' -DRBEXT_VISIBILITY=1    -I./../contrib/lz4/lib -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fvisibility=hidden -m64 -o hashargs.o -c hashargs.c
gcc -I. -I/opt/rh/rh-ruby25/root/usr/include -I/opt/rh/rh-ruby25/root/usr/include/ruby/backward -I/opt/rh/rh-ruby25/root/usr/include -I. '-DRBEXT_API=__attribute__ ((visibility("default")))' -DRBEXT_VISIBILITY=1    -I./../contrib/lz4/lib -fPIC -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fvisibility=hidden -m64 -o lz4_amalgam.o -c lz4_amalgam.c
rm -f extlz4.so
gcc -shared -o extlz4.so blockapi.o extlz4.o frameapi.o hashargs.o lz4_amalgam.o -L. -L/opt/rh/rh-ruby25/root/usr/lib64 -L. -Wl,-z,relro -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-z,relro  -m64  -m64  -lruby  -lpthread -ldl -lcrypt -lm   -lc
current directory: /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/extlz4-0.3/ext
make "DESTDIR=" install
/usr/bin/mkdir -p . ./.gem.20200603-1029-b6hxzf/2.5
exit > .sitearchdir.-.2.5.time
/usr/bin/install -c -m 0755 extlz4.so ./.gem.20200603-1029-b6hxzf/2.5

/opt/rh/rh-ruby25/root/usr/local/bin/extlz4
Successfully installed extlz4-0.3
....
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/lz4_codec.rb
....
139 gems installed
INFO: all gems installed successfully
```
number of gems without extlz4 is 138 (from cloned git repo version 4.6)

/var/log/fluentd/fluentd.log
```
2020-06-03 16:37:19 +0200 [warn]: Send exception occurred: using lz4 compression requires adding a dependency on the `extlz4` gem to your Gemfile.
2020-06-03 16:37:19 +0200 [warn]: Exception Backtrace : /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/lz4_codec.rb:16:in `rescue in load'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/lz4_codec.rb:13:in `load'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/compression.rb:30:in `find_codec'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/compressor.rb:28:in `initialize'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:45:in `new'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:45:in `topic_producer'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/out_kafka2.rb:227:in `write'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2020-06-03 16:37:19 +0200 [warn]: thread exited by unexpected error plugin=Fluent::Kafka2Output title=:flush_thread_0 error_class=LoadError error="using lz4 compression requires adding a dependency on the `extlz4` gem to your Gemfile."
#<Thread:0x00007fc6617af768@flush_thread_0@/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin_helper/thread.rb:70 run> terminated with exception (report_on_exception is true):
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/lz4_codec.rb:16:in `rescue in load': using lz4 compression requires adding a dependency on the `extlz4` gem to your Gemfile. (LoadError)
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/lz4_codec.rb:13:in `load'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/compression.rb:30:in `find_codec'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/ruby-kafka-1.0.0/lib/kafka/compressor.rb:28:in `initialize'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:45:in `new'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/kafka_producer_ext.rb:45:in `topic_producer'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluent-plugin-kafka-0.13.0/lib/fluent/plugin/out_kafka2.rb:227:in `write'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
        from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/fluentd-1.9.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

**Comment by jcantrill** [comment]
Did you run this after updating the Gemfile?  https://github.com/openshift/origin-aggregated-logging/blob/master/hack/update-fluentd-vendor-gems.sh

**Comment by johnny-burak** [comment]
Installation of gem extlz4 in v 0.3.1 fixed. https://github.com/dearblue/ruby-extlz4/issues/2.

Please add extlz4 to the fluentd image.
