### ISSUE TITLE
Cluster readers cannot view operations index.

### ISSUE THREAD

**Issue by pat2man** [openshift/origin-aggregated-logging#335]
Users with the `cluster-admin` permission can see the operations index but those with `cluster-reader` cannot. It seems logical that users with read permission should be able to see everything.

**Comment by richm** [comment]
See https://github.com/openshift/origin-aggregated-logging/tree/master/deployer#using-kibana "openshift.operations.allow_cluster_reader"

**Comment by RaymondArias** [comment]
I did the <code>oc edit configmap/logging-elasticsearch</code> and changed the openshift.operations.allow_cluster_reader to true
<p></p>
<code>
apiVersion: v1
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME}

    script:
      inline: on
      indexed: on

    index:
      number_of_shards: 1
      number_of_replicas: 0
      auto_expand_replicas: 0-3
      unassigned.node_left.delayed_timeout: 2m
      translog:
        flush_threshold_size: 256mb
        flush_threshold_period: 5m

    node:
      master: true
      data: true

    network:
      host: 0.0.0.0

    cloud:
      kubernetes:
        service: ${SERVICE_DNS}
        namespace: ${NAMESPACE}

    discovery:
      type: kubernetes
      zen.ping.multicast.enabled: false

    gateway:
      expected_master_nodes: ${NODE_QUORUM}
      recover_after_nodes: ${RECOVER_AFTER_NODES}
      expected_nodes: ${RECOVER_EXPECTED_NODES}
      recover_after_time: ${RECOVER_AFTER_TIME}

    io.fabric8.elasticsearch.authentication.users: ["system.logging.kibana", "system.logging.fluentd", "system.logging.curator", "system.admin"]

    openshift.config:
      use_common_data_model: true
      project_index_prefix: "project"
      time_field_name: "@timestamp"

    openshift.searchguard:
      keystore.path: /etc/elasticsearch/secret/admin.jks
      truststore.path: /etc/elasticsearch/secret/searchguard.truststore

    openshift.operations.allow_cluster_reader: true
</code>
<p></p>
<p>And restarted the ES cluster however I continue to get these logs from ES</p>
<p></p>
<code>
[2017-02-23 19:04:52,476][ERROR][io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter] [Ocelot] Exception determining user's role.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/oapi/v1/clusterrolebindings/cluster-admins. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:310)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:261)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:225)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:559)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:134)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.isOperationsUser(DynamicACLFilter.java:299)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.process(DynamicACLFilter.java:207)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:264)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:161)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:153)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:101)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:451)
	at com.floragunn.searchguard.ssl.http.netty.SearchGuardSSLNettyHttpServerTransport.dispatchRequest(SearchGuardSSLNettyHttpServerTransport.java:162)
	at com.floragunn.searchguard.http.SearchGuardHttpServerTransport.dispatchRequest(SearchGuardHttpServerTransport.java:70)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:61)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</code>

**Comment by richm** [comment]
What version of origin/ocp are you using?

**Comment by RaymondArias** [comment]
Openshift 3.3.1.3
Kubernetes v1.3.0

**Comment by richm** [comment]
@ewolinetz Is the cluster_reader feature supported in OCP 3.3?

**Comment by ewolinetz** [comment]
It looks like the Elasticsearch service account is missing a role binding.
From [1] :
In order for Elasticsearch to correctly check the role bindings for users it will need to be added to an additional role (note, change `:logging:` below to the project of your choice):
```
$ oadm policy add-cluster-role-to-user rolebinding-reader \
       system:serviceaccount:logging:aggregated-logging-elasticsearch
```


[1] https://github.com/openshift/origin-aggregated-logging/tree/master/deployer#create-supporting-service-accounts-and-permissions

**Comment by RaymondArias** [comment]
That command fixed the issue. Thank you

**Comment by ewolinetz** [comment]
Glad to hear that resolved it! 
Closing this issue per https://github.com/openshift/origin-aggregated-logging/issues/335#issuecomment-282313513
