### ISSUE TITLE
Timeout error in logging-es container logs

### ISSUE THREAD

**Issue by deanpeterson** [openshift/origin-aggregated-logging#395]
Connection #0 to host localhost left intact
{"acknowledged":true}[2017-04-27 04:55:32,074][ERROR][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [Rafferty] Timeout java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, actiongroups](index=.searchguard.logging-es-fnenevd6-1-l51uf)
java.util.concurrent.TimeoutException: Timeout after 30SECONDS while retrieving configuration for [config, roles, rolesmapping, actiongroups](index=.searchguard.logging-es-fnenevd6-1-l51uf)
	at com.floragunn.searchguard.configuration.ConfigurationLoader.load(ConfigurationLoader.java:97)
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:262)
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.nodeOperation(TransportConfigUpdateAction.java:62)
	at org.elasticsearch.action.support.nodes.TransportNodesAction.nodeOperation(TransportNodesAction.java:93)
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:229)
	at org.elasticsearch.action.support.nodes.TransportNodesAction$NodeTransportHandler.messageReceived(TransportNodesAction.java:225)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService.messageReceivedDecorate(SearchGuardSSLTransportService.java:171)
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:278)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:138)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:293)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Followed by

[2017-04-27 04:55:37,794][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] .kibana does not exist in cluster metadata
[2017-04-27 05:08:55,884][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] logstash-* does not exist in cluster metadata
[2017-04-27 05:08:55,886][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] logstash-* does not exist in cluster metadata
[2017-04-27 05:13:07,126][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.management-infra.6ae4355a-1a81-11e7-bf5e-6805ca461d43.* does not exist in cluster metadata
[2017-04-27 05:13:07,127][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.management-infra.6ae4355a-1a81-11e7-bf5e-6805ca461d43.* does not exist in cluster metadata
[2017-04-27 05:13:07,127][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.management-infra.6ae4355a-1a81-11e7-bf5e-6805ca461d43.* does not exist in cluster metadata
[2017-04-27 05:13:13,759][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] project.logging.d325561b-2ac5-11e7-bb8c-6805ca461d43.* does not exist in cluster metadata

**Comment by jcantrill** [comment]
Can you please provide additional details of your set up?  Suggestions of items that would be useful: https://github.com/jcantrill/origin-aggregated-logging/blob/1bbef826cb432f2a8c37577d1bd7f8fa52589e3b/docs/issues.md

**Comment by jcantrill** [comment]
Closing inactivity
