### ISSUE TITLE
OCP 3.4 -> 3.5 Update failed search-guard error

### ISSUE THREAD

**Issue by mjudeikis** [openshift/origin-aggregated-logging#436]
Updated succeeded using standard ansible playbooks, but cluster is not responding.

```
[ocpadmin@806783-jbox1 ~]$ oc logs -f logging-es-7u71p157-6-gkw6l
Comparing the specificed RAM to the maximum recommended for ElasticSearch...
Inspecting the maximum RAM available...
ES_JAVA_OPTS: '-Dmapper.allow_dots_in_name=true -Xms128M -Xmx4096m'
Checking if Elasticsearch is ready on https://localhost:9200 ..............................................Will connect to localhost:9300 ... done
Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...
ERR: Timed out while waiting for a green or yellow cluster state.
   * Try running sgadmin.sh with -icl and -nhnv (If thats works you need to check your clustername as well as hostnames in your SSL certificates)
```

All 3 boxes are same.

```
/usr/share/java/elasticsearch/plugins/search-guard-2/tools/sgadmin.sh -nhnv -ts /etc/elasticsearch/secret/searchguard.truststore -ks /etc/elasticsearch/secret/searchguard.key
Will connect to localhost:9300 ... done
ERR: An unexpected ElasticsearchSecurityException occured: Error while initializing transport SSL layer: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
Trace:
ElasticsearchSecurityException[Error while initializing transport SSL layer: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.]; nested: IOException[DerInputStream.getLength(): lengthTag=109, too big.];
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:262)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.<init>(DefaultSearchGuardKeyStore.java:139)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:40)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:128)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:141)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:315)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:101)
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:599)
	at sun.security.util.DerValue.init(DerValue.java:365)
	at sun.security.util.DerValue.<init>(DerValue.java:320)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1914)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at com.floragunn.searchguard.ssl.DefaultSearchGuardKeyStore.initSSLConfig(DefaultSearchGuardKeyStore.java:208)
	... 7 more

```

```
penssl x509 -in admin-ca -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = logging-signer-test
        Validity
            Not Before: May 23 15:41:05 2017 GMT
            Not After : May 22 15:41:06 2022 GMT
        Subject: CN = logging-signer-test
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
```

**Comment by ljuaneda** [comment]
I'm stuck with the same issue after upgrading form 3.4 to 3.5.
I've got 2 clusters: es and es-ops. es-ops is fine.

ES data is persistent with an hostPath mount. When I set it back to emptyDir, es is running fine, but when I mount my data with hostPath, it goes timed-out.

Have you found any solution ?

**Comment by jcantrill** [comment]
@ljuaneda You most likely have a situation where the seeding of SG times out and you  now unable to access data.  If you are using images from origin then this [1] should resolve your issues.  We are currently in the process of moving similiar changes to downstream code now which should land with the next errata.

In the meantime, you can exec into the pod, cat the run.sh, and run the 'seed sgl' command to seed the SG index.  You may still experience timeout issues if the cluster is not in a yellow state which may require you to wait or delete 'red' indexes which are not of importance to you.  @portante  do you have additional suggestions?

[1] https://github.com/openshift/origin-aggregated-logging/pull/469

**Comment by ljuaneda** [comment]
We are using OCPv3.5.5.15 with logging 3.5.0-11

**Comment by portante** [comment]
@ljuaneda, you need to check the health state of the Elasticsearch instance running with your `hostPath`.  It does not make a lot of sense to start an ES instance with `emptyDir`, as ES will replicate data from other members to the local ephemeral drive of the pod and cause other problems.

Consider using this [gist](https://gist.github.com/portante/0b294318c68dc362481e2994b9030200) to determine the current health and the resolve the problem indexes.

**Comment by ljuaneda** [comment]
It seems there is a pb with a searchgard index

```
[wnradm@SIY05TY002:~]$ oc -n logging exec logging-es-dqikd3oj-24-mln6r -- check_es_state.sh
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"check_es_state.sh\\\": executable file not found in $PATH\"\n"
[wnradm@SIY05TY002:~]$ oc -n logging exec logging-es-dqikd3oj-24-mln6r -- ./check_es_state.sh
Thu Jun 22 08:13:49 UTC 2017
epoch      timestamp cluster    status node.total node.data shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1498119229 08:13:49  logging-es red             3         3   1353 451    0    0       18             0                  -                 98.7%
host         ip           heap.percent ram.percent  load node.role master name
10.130.8.117 10.130.8.117            4          41 27.68 d         m      Ororo Munroe
10.128.8.108 10.128.8.108            3          51  3.82 d         *      Mesmero
10.129.8.111 10.129.8.111            3          38  1.97 d         m      Doctor Glitternight
health status index                                                                      pri rep docs.count docs.deleted store.size pri.store.size
red    open   .searchguard.logging-es-dqikd3oj-6-wdzqg                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-9-bg4jc                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-9-6z0jm                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-9-30fxt                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-7-3bm0r                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-8-i3cvg                                     1   2
green  open   .searchguard.logging-es-wty0md81-7-zuwuj                                     1   2          4            0     59.8kb         19.9kb
red    open   .searchguard.logging-es-dqikd3oj-6-wdzqg                                     1   2
red    open   .searchguard.logging-es-dqikd3oj-9-bg4jc                                     1   2
green  open   .searchguard.logging-es-wty0md81-9-m1btu                                     1   2          4            0     67.8kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-14-fmpad                                    1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-lj0vt                                     1   2          4            0     75.7kb         25.2kb
red    open   .searchguard.logging-es-dqikd3oj-9-6z0jm                                     1   2
green  open   .searchguard.logging-es-wty0md81-3-s4s6k                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-1p1fn                                     1   2          4            0      294kb           98kb
green  open   .searchguard.logging-es-wty0md81-9-5rk1z                                     1   2          4            0    293.9kb         97.9kb
green  open   .searchguard.logging-es-dqikd3oj-5-uyvsw                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-2upzg                                     1   2          4            0    277.5kb         92.5kb
green  open   .searchguard.logging-es-dqikd3oj-3-zqise                                     1   2          4            0     97.2kb         32.4kb
green  open   .searchguard.logging-es-dqikd3oj-16-j4lsp                                    1   2          4            2    298.4kb        100.2kb
green  open   .searchguard.logging-es-wty0md81-9-qnt84                                     1   2          4            0      257kb         85.6kb
green  open   .searchguard.logging-es-dqikd3oj-3-leisz                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-g8fgd                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-3-56tpk                                     1   2          4            0     97.2kb         32.4kb
green  open   .searchguard.logging-es-dqikd3oj-3-g05zz                                     1   2          4            2    103.9kb         34.6kb
green  open   .searchguard.logging-es-k4ijvqcm-3-61gy5                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-9-btxan                                     1   2          4            0    288.6kb         96.2kb
green  open   .searchguard.logging-es-k4ijvqcm-3-3m697                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-4-e0wro                                     1   2          4            0    102.9kb         34.3kb
green  open   .searchguard.logging-es-wty0md81-9-d2ufq                                     1   2          4            0     67.8kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-7-2d6cz                                     1   2          4            2      265kb         88.3kb
green  open   .searchguard.logging-es-dqikd3oj-10-hgiue                                    1   2          4            0       52kb         17.3kb
green  open   .searchguard.logging-es-dqikd3oj-3-rzaxm                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-16-uz3xl                                    1   2          4            0    277.5kb         92.5kb
green  open   .searchguard.logging-es-k4ijvqcm-9-wthcv                                     1   2          4            0      257kb         85.6kb
green  open   .searchguard.logging-es-wty0md81-3-ix733                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-5-17s0h                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-4-0gbq7                                     1   2          4            0     75.7kb         25.2kb
red    open   .searchguard.logging-es-dqikd3oj-9-30fxt                                     1   2
green  open   .searchguard.logging-es-wty0md81-9-s6k8c                                     1   2          4            0      294kb           98kb
green  open   .searchguard.logging-es-wty0md81-9-s4uz9                                     1   2          4            0    277.5kb         92.5kb
green  open   .searchguard.logging-es-wty0md81-5-8gtqd                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-9-d7a1z                                     1   2          0            0       477b           159b
green  open   .searchguard.logging-es-dqikd3oj-12-uyye7                                    1   2          4            0       52kb         17.3kb
green  open   .searchguard.logging-es-dqikd3oj-16-rsfd1                                    1   2          4            0      257kb         85.6kb
green  open   .searchguard.logging-es-dqikd3oj-16-mbf7v                                    1   2          0            0       477b           159b
green  open   .searchguard.logging-es-wty0md81-6-s2mli                                     1   2          4            0       52kb         17.3kb
green  open   .searchguard.logging-es-dqikd3oj-13-qeu5n                                    1   2          4            0    267.7kb         89.2kb
green  open   .searchguard.logging-es-dqikd3oj-11-hscky                                    1   2          0            0       479b           159b
green  open   .searchguard.logging-es-wty0md81-7-twzlp                                     1   2          4            0    261.1kb           87kb
green  open   .searchguard.logging-es-dqikd3oj-3-e7k3t                                     1   2          4            0     75.7kb         25.2kb
red    open   .searchguard.logging-es-dqikd3oj-7-3bm0r                                     1   2
green  open   .searchguard.logging-es-k4ijvqcm-9-am212                                     1   2          4            0     73.2kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-13-chgzs                                    1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-3-yc0yi                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-501gn                                     1   2          4            0    290.8kb         96.2kb
green  open   .searchguard.logging-es-k4ijvqcm-4-cd2wz                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-4-asqdm                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-16-3sjs4                                    1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-7-vctxo                                     1   2          4            2    274.7kb         91.5kb
green  open   .searchguard.logging-es-k4ijvqcm-5-t1zwo                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-3-rwa09                                     1   2          4            0     97.2kb         32.4kb
green  open   .searchguard.logging-es-dqikd3oj-13-0fb1x                                    1   2          4            1    271.2kb         90.4kb
green  open   .searchguard.logging-es-dqikd3oj-14-6kna6                                    1   2          4            0       68kb         22.6kb
green  open   .searchguard.logging-es-dqikd3oj-16-kwxnf                                    1   2          4            0      294kb           98kb
green  open   .searchguard.logging-es-dqikd3oj-4-q8grd                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-3-ydu0e                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-9-3tmpm                                     1   2          4            0       52kb         17.3kb
green  open   .searchguard.logging-es-dqikd3oj-16-arv9p                                    1   2          4            0    290.8kb         96.2kb
green  open   .searchguard.logging-es-k4ijvqcm-7-roke6                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-wty0md81-3-yy7y7                                     1   2          4            0     97.2kb         32.4kb
green  open   .searchguard.logging-es-k4ijvqcm-3-zokbn                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-4-voqz7                                     1   2          4            0     95.3kb         31.7kb
green  open   .searchguard.logging-es-k4ijvqcm-6-m2tzm                                     1   2          4            0       52kb         17.3kb
green  open   .searchguard.logging-es-k4ijvqcm-7-73x6v                                     1   2          4            2    263.7kb         87.9kb
green  open   .searchguard.logging-es-k4ijvqcm-3-matk3                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-dqikd3oj-16-4ebyy                                    1   2          4            0     67.8kb         17.3kb
red    open   .searchguard.logging-es-dqikd3oj-8-i3cvg                                     1   2
green  open   .searchguard.logging-es-wty0md81-3-a88kj                                     1   2          4            0     75.7kb         25.2kb
green  open   .searchguard.logging-es-k4ijvqcm-7-gz93j                                     1   2          4            0     70.4kb         19.9kb
green  open   .searchguard.logging-es-wty0md81-4-oeuma                                     1   2          4            0    102.9kb         34.3kb
epoch      timestamp count
1498119230 08:13:50  127855159
epoch      timestamp count
1498119235 08:13:55  127855159
Thu Jun 22 08:13:55 UTC 2017
```

**Comment by portante** [comment]
@ljuaneda, delete all those .searchguard indices and restart all the ES pods to see if this clears up.

**Comment by ljuaneda** [comment]
I did that, problem is gone 
thank you
