### ISSUE TITLE
Error accessing _all index using Kibana user

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/origin-aggregated-logging#59]
This might be issue in Search-Guard configuration but still I think it is worth recording.

When I setup origin-aggregated-logging stack (see below if details are needed about how I did it) then I spotted difference between the following two calls. In case of the first call we use `_all` index placeholder  (or it can be omitted at all) and it gets rejected by SG, while in the second call we explicitly used `*` and it is ok.

``` shell
$ sudo curl -s -k --cert ./cert --key ./key https://localhost:9200/_cat/count
# or
$ sudo curl -s -k --cert ./cert --key ./key https://localhost:9200/_cat/count/_all
{
  "error" : "RuntimeException[java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/count and User [name=system.logging.kibana, roles=[]]]; nested: RuntimeException[Attempt from null to _all indices for indices:data/read/count and User [name=system.logging.kibana, roles=[]]]; ",
  "status" : 500
}
```

vs.

``` shell
$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/_cat/count/*?v'
epoch      timestamp count 
1455109195 12:59:55  6797
```

Another example of this issue can be the following (probably more simple) use case:

``` shell
$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/_search?size=0'
# or
$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/_all/_search?size=0'
{
  "error" : "RuntimeException[java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/search and User [name=system.logging.kibana, roles=[]]]; nested: RuntimeException[Attempt from null to _all indices for indices:data/read/search and User [name=system.logging.kibana, roles=[]]]; ",
  "status" : 500
}
```

vs.

``` shell
$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/*/_search?size=0'
{
  "took" : 9,
  "timed_out" : false,
  "_shards" : {
    "total" : 20,
    "successful" : 20,
    "failed" : 0
  },
  "hits" : {
    "total" : 7374,
    "max_score" : 0.0,
    "hits" : []
  }
}
```

Internally, it probably results into different calls, however, functionally it should be equivalent. The question is, shall we care about rejection of use of `_all` index while `*` is ok? May be we need to review ACL rules a bit more?

This might be related to #31?
### Stack setup

I started OpenShift using vagrant from origin repo (checked out `v1.1.1` tag before I built it). After I `ssh`-ed to `openshiftdev` machine I used [@richm's script](https://github.com/richm/scripts/blob/master/oshift-logging-setup.sh) to build and setup whole stack. This means that I end up using kibana user certificates when doing above `curl` commands.

**Comment by ewolinetz** [comment]
I don't believe this is directly related to #31, however it is probably an ACL related configuration as well.  Internally ES may have an action for `_all`, which is a different path than "*" like you're using above.  What do the ES logs look like when you try to use `_all`?  The Searchguard exception should give us a better idea what action it is using.

**Comment by lukas-vlcek** [comment]
### Exception stack trace for the `/_cat/count` API call

`$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/_cat/count/?v'`

````
[2016-02-11 08:55:50,355][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Attempt from null to _all indices for indices:data/read/count and User [name=system.logging.kibana, roles=[]]
[2016-02-11 08:55:50,369][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/count and User [name=system.logging.kibana, roles=[]] for action indices:data/read/count
java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/count and User [name=system.logging.kibana, roles=[]]
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:195)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:64)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at io.fabric8.elasticsearch.plugin.ActionForbiddenActionFilter.apply(ActionForbiddenActionFilter.java:48)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.FLSActionFilter.applySecure(FLSActionFilter.java:76)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.DLSActionFilter.applySecure(DLSActionFilter.java:73)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.RequestActionFilter.applySecure(RequestActionFilter.java:94)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.FilterClient.execute(FilterClient.java:66)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.execute(BaseRestHandler.java:92)
	at org.elasticsearch.client.support.AbstractClient.count(AbstractClient.java:379)
	at org.elasticsearch.rest.action.cat.RestCountAction.doRequest(RestCountAction.java:70)
	at org.elasticsearch.rest.action.cat.AbstractCatAction.handleRequest(AbstractCatAction.java:66)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:225)
	at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:299)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:280)
	at io.fabric8.elasticsearch.plugin.KibanaUserReindexFilter.process(KibanaUserReindexFilter.java:76)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at com.floragunn.searchguard.rest.DefaultRestFilter.processSecure(DefaultRestFilter.java:37)
	at com.floragunn.searchguard.rest.AbstractACRestFilter.process(AbstractACRestFilter.java:198)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.process(DynamicACLFilter.java:154)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:329)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.floragunn.searchguard.http.netty.MutualSSLHandler.messageReceived(MutualSSLHandler.java:80)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

### Exception stack trace for the `/_all/_search` API call:

`$ sudo curl -s -k --cert ./cert --key ./key 'https://localhost:9200/_all/_search'`

````
[2016-02-11 08:56:58,201][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Attempt from null to _all indices for indices:data/read/search and User [name=system.logging.kibana, roles=[]]
[2016-02-11 08:56:58,205][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/search and User [name=system.logging.kibana, roles=[]] for action indices:data/read/search
java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/search and User [name=system.logging.kibana, roles=[]]
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:195)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:64)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at io.fabric8.elasticsearch.plugin.ActionForbiddenActionFilter.apply(ActionForbiddenActionFilter.java:48)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.FLSActionFilter.applySecure(FLSActionFilter.java:76)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.DLSActionFilter.applySecure(DLSActionFilter.java:73)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at com.floragunn.searchguard.filter.RequestActionFilter.applySecure(RequestActionFilter.java:94)
	at com.floragunn.searchguard.filter.AbstractActionFilter.apply(AbstractActionFilter.java:97)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:165)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:82)
	at org.elasticsearch.client.node.NodeClient.execute(NodeClient.java:98)
	at org.elasticsearch.client.FilterClient.execute(FilterClient.java:66)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.execute(BaseRestHandler.java:92)
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
	at org.elasticsearch.rest.action.search.RestSearchAction.handleRequest(RestSearchAction.java:81)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:53)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:225)
	at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:299)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:280)
	at io.fabric8.elasticsearch.plugin.KibanaUserReindexFilter.process(KibanaUserReindexFilter.java:76)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at com.floragunn.searchguard.rest.DefaultRestFilter.processSecure(DefaultRestFilter.java:37)
	at com.floragunn.searchguard.rest.AbstractACRestFilter.process(AbstractACRestFilter.java:198)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at io.fabric8.elasticsearch.plugin.acl.DynamicACLFilter.process(DynamicACLFilter.java:154)
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:329)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
	at com.floragunn.searchguard.http.netty.MutualSSLHandler.messageReceived(MutualSSLHandler.java:80)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by ewolinetz** [comment]
@lukas-vlcek this should be possible to do now with the admin-cert that is provided as part of the elasticsearch secret.  Can you please confirm?

**Comment by richm** [comment]
@lukas-vlcek Please confirm so we can either close this issue or fix it.

**Comment by lukas-vlcek** [comment]
@ewolinetz tried today using <https://github.com/openshift-evangelists/vagrant-origin>.

When I log to elasticsearch pod then this is what I get:

````
$ curl -s -k  https://logging-es:9200/_search?size=0 \
  --cert /etc/elasticsearch/secret/admin-cert \
  --key /etc/elasticsearch/secret/admin-key
{"error":"ForbiddenException[Attempt from null to _all indices for indices:data/read/search and User [name=system.admin, roles=[]]]","status":403}
````

vs.

````
$ curl -s -k  https://logging-es:9200/*/_search?size=0 \
  --cert /etc/elasticsearch/secret/admin-cert \
  --key /etc/elasticsearch/secret/admin-key
{"took":27,"timed_out":false,"_shards":{"total":20,"successful":20,"failed":0},"hits":{"total":11356,"max_score":0.0,"hits":[]}} 
````

Note `logging-es:9200/_search` vs `logging-es:9200/*/_search`.

But may be I am still using old docker images?:
````
# oc status
In project openshift-infra on server https://10.2.2.2:8443

[... cut out heapster and hawkular stuff ...]

svc/logging-es - 172.30.103.197:9200 -> restapi
  dc/logging-es-6pdceejp deploys docker.io/openshift/origin-logging-elasticsearch:latest (manual)
    deployment #1 deployed 47 minutes ago - 1 pod

svc/logging-es-cluster (headless):9300
  dc/logging-es-6pdceejp deploys docker.io/openshift/origin-logging-elasticsearch:latest (manual)
    deployment #1 deployed 47 minutes ago - 1 pod

svc/logging-es-ops - 172.30.35.139:9200 -> restapi

svc/logging-es-ops-cluster (headless):9300

https://kibana.apps.10.2.2.2.xip.io (reencrypt) (svc/logging-kibana)
  dc/logging-kibana deploys (manual)
    docker.io/openshift/origin-logging-kibana:latest
    deployment #1 deployed 47 minutes ago - 1 pod
    docker.io/openshift/origin-logging-auth-proxy:latest
    deployment #1 deployed 47 minutes ago - 1 pod

https://kibana-ops.example.com (reencrypt) (svc/logging-kibana-ops)

dc/logging-curator deploys docker.io/openshift/origin-logging-curator:latest (manual)
  deployment #1 deployed 47 minutes ago - 1 pod

pod/logging-fluentd-hr7ch runs docker.io/openshift/origin-logging-fluentd:latest
````

**Comment by ewolinetz** [comment]
Is the difference just that ES isn't automatically mapping a rest endpoing without a defined index to `*` or `_all` ?  I've never tried to do it that way, I've always added a base index for the action to apply to - `logging-es:9200/*/_search`.

**Comment by ewolinetz** [comment]
@lukas-vlcek can you confirm that 
`curl 'https://localhost:9200/_cat/count'` fails
but
`curl 'https://localhost:9200/*/_cat/count'` works?

I receive a 404 when doing the second command but I receive the same error as you're seeing with the top one

**Comment by ewolinetz** [comment]
After playing around with the SG ACL, even if i explicitly use the indices "*" and "_all" for the admin, things like `_all/_cat/_count` fail, but `*/_cat/_count` succeed... I'm going to investigate how SG does its expansion. we may need to carry a patch for our 1.5 branch

**Comment by lukas-vlcek** [comment]
I do not think there is anything like`_all/_cat/...` so this should really fail.

The [_cat API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html) is the top level one (always following `<es_host:port>`) having several options following it. Nice thing about _cat API is that if you call just `curl localhost:9200/_cat` without any other options it will return all the options it provides.

For example the [`count API`](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-count.html) endpoint should be something like `_cat/count/{indices}`. Which means that the following options should be equal (all returning info for all indices):

- `_cat/count`
- `_cat/count/_all`
- `_cat/count/*`

While `_cat/count/index1` returns info for `index1` only.

**Comment by sosiouxme** [comment]
Related bug, https://bugzilla.redhat.com/show_bug.cgi?id=1373611 for `/_cat/indices` not working.

**Comment by ewolinetz** [comment]
This appears to be fixed with the latest version of SG (for ES 2.3.5)

**Comment by richm** [comment]
Can we close this issue?

**Comment by jcantrill** [comment]
@ewolinetz thoughts on closing this issue since our move to ES2.4.x

**Comment by ewolinetz** [comment]
@lukas-vlcek can you please confirm if you still see this with the latest ES image we provide?
