### ISSUE TITLE
Unknown Discovery type [Kubernetes]

### ISSUE THREAD

**Issue by zuaresc** [openshift/origin-aggregated-logging#677]
Upgraded cluster to Origin 3.6 and tried to re-provision logging. No matter what I do, I always get this error when ES is starting up.

`[2017-09-23 16:39:43,791][INFO ][container.run            ] Begin Elasticsearch startup script
[2017-09-23 16:39:43,795][INFO ][container.run            ] Comparing the specified RAM to the maximum recommended for Elasticsearch...
[2017-09-23 16:39:43,796][INFO ][container.run            ] Inspecting the maximum RAM available...
[2017-09-23 16:39:43,799][INFO ][container.run            ] ES_HEAP_SIZE: '4096m'
[2017-09-23 16:39:43,801][INFO ][container.run            ] Setting heap dump location /elasticsearch/persistent/heapdump.hprof
[2017-09-23 16:39:43,804][INFO ][container.run            ] Checking if Elasticsearch is ready on https://localhost:9200
Exception in thread "main" java.lang.IllegalArgumentException: Unknown Discovery type [kubernetes]
	at org.elasticsearch.discovery.DiscoveryModule.configure(DiscoveryModule.java:100)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
Refer to the log for complete error details.`

Using this playbook (checked out latest 3.6 of the openshift-ansible repo):
`openshift-ansible/playbooks/byo/openshift-cluster/openshift-logging.yml`

Relevant parts of my inventory file:
`containerized=false
openshift_logging_image_version=v3.6.0
openshift_logging_install_logging=true
openshift_logging_use_ops=false
openshift_logging_kibana_hostname="kibana.apps.example.com"
openshift_logging_master_public_url="https://openshift-master.example.com"
openshift_logging_curator_default_days=30
openshift_logging_es_cluster_size=3
openshift_logging_kibana_nodeselector={'role': 'infra'}
openshift_logging_es_nodeselector={'role': 'infra'}
openshift_logging_curator_nodeselector={'role': 'infra'}`

I can provide additional information if needed.

**Comment by richm** [comment]
@wozniakjan

**Comment by wozniakjan** [comment]
@zuaresc this is the same issue with a solution: https://github.com/openshift/openshift-ansible/issues/5497#issuecomment-331372471

**Comment by zuaresc** [comment]
Looks like it's working now. Thanks!

**Comment by mjudeikis** [comment]
@wozniakjan What is ETA to port ElastiSearch image changes to 3.6 Image in the registry.access.redhat.com registry? I would assume if we make changes to release-3.6 branch, we do same for image?

**Comment by wozniakjan** [comment]
@mjudeikis I don't really know, maybe some release engineer could provide an answer. It looks like in the past they were released in a monthly cycle but currently getting a bit of a delay

https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/logging-elasticsearch

**Comment by jcantrill** [comment]
@mjudeikis Images that end up in registry.access.redhat.com are beholden to our release engineering process of which we do not have any direct control.  I suggest you reach out to the release engineering team for additional information.  Fixes for errata follow the Openshift team sprint cycle cadence which is approximately every 3 weeks.  The next release is tentatively scheduled for Oct. 27
