### ISSUE TITLE
"Error: SELF_SIGNED_CERT_IN_CHAIN" after upgrading to v1.5.1

### ISSUE THREAD

**Issue by gfvirga** [openshift/origin-aggregated-logging#936]
Hello,

I've been trying to upgrade my EFK environment from 1.4.1 to 1.5.1. The ansible-playbook deployment worked fine and all of the pod started successfully.
Although, when we try to launch kibana, the kibana-proxy container crashes and produces the following log:
Starting up the proxy with auth mode "oauth2" and proxy transform "user_header,token_header".
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SELF_SIGNED_CERT_IN_CHAIN
    at SecurePair.<anonymous> (tls.js:1381:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:980:10)
    at CleartextStream.read [as _read] (tls.js:472:13)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)

Has anyone come across to this?
I have tried deleting oauthclient/kibana-proxy and recreating with the ansible-playbook, but it didn't work.

I performed the same upgrade in another environment and it worked without problems.

Any help would be gratefully appreciated. 

Thank you,
Gabriel Virga

**Comment by jcantrill** [comment]
Closing stale
